spring.application.name=pawsitter

# --- Server ---
server.port=${SERVER_PORT:3400}

# --- Database ---
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/pawsitter}
spring.datasource.username=${DB_USERNAME:pawsitter}
spring.datasource.password=${DB_PASSWORD:pawsitter_password}

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Multipart ---
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# --- JWT / Security ---
#Should later take care of keeping it hidden
app.jwt.secret=f3sM23jmDVwL7KIk5FTsJGYVvkj2acW2LJaB8QNsaHouiHv0YTeo6htrvjjl0EfbPAKiZDC7bWLj661w31TFXEw==
app.jwt.expiration-ms=3600000

# --- MailerSend API ---
#Should later take care of keeping it hidden
mailersend.base-url=https://api.mailersend.com/v1
mailersend.token=${MAILERSEND_TOKEN:mlsn.8ffaa800f2e300d6d80298f35f05ec6938790c674724244f31c376925d43e937}