name: Deploy PawSitter

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: pawsitter-deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code

        uses: actions/checkout@v5

      - name: Create environment file
        run: |
          cat > .env <<EOF
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          MAILERSEND_TOKEN=${{ secrets.MAILERSEND_TOKEN }}
          FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
          EOF

        #secrets are hidden from Actions log:
      - name: Validate Compose
        run: docker compose -f compose.yaml config --quiet

      - name: Stop old containers
        run: docker compose -f compose.yaml down --remove-orphans

      - name: Build and start PawSitter
        run: docker compose -f compose.yaml up -d --build

      - name: Check containers
        run: docker compose -f compose.yaml ps

      # || true - log step non-failing if container doesn't exist
      - name: Show application logs
        if: always()
        run: docker compose -f compose.yaml logs --tail 100 app || true

